### ISSUE TITLE
A Quick Suggestion (For Next Update Possibly).

### ISSUE THREAD

**Issue by Walegy** [GaryOderNichts/Bloopair#102]
I have a crazy good suggestion that was offered here in issues, yet I am not sure if it has been implemented... Personally, I would like to see audio support for headphone jacked controllers that connect through Bloopair! It would be intruiging to see this implemented, as well as having a way to connect the headphone jack other than the Gamepad.

**Comment by GaryOderNichts** [comment]
Duplicate of #62.
