### ISSUE TITLE
Wiiu freezes when I open Bloopair with the homebrew menu

### ISSUE THREAD

**Issue by ja-287297** [GaryOderNichts/Bloopair#105]
I have a problem where whenever try to open Bloopair with the homebrew launcher the wiiu starts to freeze.
I'm using version 0.6.2

**Comment by GaryOderNichts** [comment]
Since Bloopair 0.5.1 the Homebrew Launcher is no longer supported. Please switch to Tiramisu/Aroma and use the setup module.

**Comment by alexprimero** [comment]
HI.  How i do that?
