### ISSUE TITLE
Failed to read local bda (Make sure bloopair is active!) error i cant fix it

### ISSUE THREAD

**Issue by Ihsan231** [GaryOderNichts/Bloopair#107]
Each time i startup bloopair this pops up and i cant connect different controllers to the console. Pls help

**Comment by GaryOderNichts** [comment]
You're not starting Bloopair, you're starting the DS3 Controller pairing tool which comes with Bloopair.
Bloopair is a setup module for Tiramisu/Aroma, make sure you're using Tiramisu/Aroma and the `30_bloopair.rpx` is in the right location.
