### ISSUE TITLE
Xbox One S controller not working

### ISSUE THREAD

**Issue by Korbclink** [GaryOderNichts/Bloopair#109]
ive done everything to set it up, but the controller just isnt pairing. Ive been able to use the joycons and ns pro controller, but not the xbox one s controller, I dont believe it is on its latest firmware (the controller).

**Comment by Invictaz** [comment]
Read the readme, the latest Xbox Controllers are now working on Bluetooth Low Energy which isn't supported by the WiiU. The only options you have is to downgrade the Xbox controller firmware, use a Cronus Zen with a Xbox Wireless adapter and HID2Vpad in Aroma.
