### ISSUE TITLE
Problems with official pro controller 

### ISSUE THREAD

**Issue by renegade2k82** [GaryOderNichts/Bloopair#118]
So after pairing they are seen as Wii remotes and not controllers and I can not play games properly and cannot go thru the Wii U menu correctly.i do not understand why there not seen as a proper controller

**Comment by GaryOderNichts** [comment]
![image](https://github.com/GaryOderNichts/Bloopair/assets/12049776/2140dc21-d104-4de0-8b0f-a3f9614fe196)
If you mean this bar up here as "they are seen as Wii remotes", that is normal. The Wii U will show all controllers using this Wii Remote symbol, even without Bloopair.
Bloopair doesn't change how official Pro Controllers work at the moment.
