### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by AlphaCraft9658** [GaryOderNichts/Bloopair#128]
I've seen that the last commit has been quite a while ago and quite a lot of open issues without any activity. Is this project still being worked on? There's a good amount of things that could be added or improved and it could be a game-changer for me.

**Comment by Invictaz** [comment]
You better ask on GaryOderNichts Discord

**Comment by GaryOderNichts** [comment]
Feel free to contribute to the project by making pull requests or helping out with issues.
