### ISSUE TITLE
A third-party Switch Pro Controller does not work

### ISSUE THREAD

**Issue by KevGam20** [GaryOderNichts/Bloopair#129]
I try to synchronize a third-party switch pro controller and it does not detect it, I have version 0.6.2

**Comment by GaryOderNichts** [comment]
Please provide more information about the controller.

**Comment by chasio2221** [comment]
a wired nintendo switch pro controller that i have will not work as well

**Comment by GaryOderNichts** [comment]
> a wired nintendo switch pro controller that i have will not work as well

Bloopair does not support wired controllers.

**Comment by GaryOderNichts** [comment]
If it's a newer third-party Switch Pro Controller, this should be fixed in [version 1.0.1](https://github.com/GaryOderNichts/Bloopair/releases/tag/v1.0.1).
