### ISSUE TITLE
Stadia-Controller in BT-Mode

### ISSUE THREAD

**Issue by elpollodiabl0** [GaryOderNichts/Bloopair#130]
You stated "Possibly, I've for now added support for all the controllers I currently own." and I wonder if this refers to the Stadia-Controller (in BT-Mode) too?
I have two of those and would love being able to user them within the Aroma environment. Right now I can not convince them of being paired.

**Comment by GaryOderNichts** [comment]
The Stadia Controller uses Bluetooth LE, which unfortunately isn't supported by the Wii Us' Bluetooth stack.
There's a note in the To-Do section in the README about it:
> Bluetooth LE support (Unlikely, only partially supported by the Bluetooth Stack)

It might be possible to support BLE using some heavy IOS-PAD patching, but for now support is unlikely and not planned.
