### ISSUE TITLE
Nintendo Switch Pro Controller won't connect

### ISSUE THREAD

**Issue by Odyssey255** [GaryOderNichts/Bloopair#146]
After the update 1.0.0, my Switch Pro Controller won't connect to Koopair, even in older versions of Bloopair.

**Comment by GaryOderNichts** [comment]
If it's a newer third-party Switch Pro Controller, this should be fixed in [version 1.0.1](https://github.com/GaryOderNichts/Bloopair/releases/tag/v1.0.1).

**Comment by Odyssey255** [comment]
It's an official one
