### ISSUE TITLE
[Suggestion] Support for the vWii games (Nintendont, WiiStation, Not64, etc ..)

### ISSUE THREAD

**Issue by RisoGalloExpresso** [GaryOderNichts/Bloopair#156]
Currently, my unofficial Nintendo Switch controller (by ECHTPower) works perfectly with all my Wii U games. all of this thanks to the Bloopair project! However, I'm curious about other games emulated in vWii mode.

Nintendont (GameCube emulator) and WiiStation (PSX emulator) support the Wii U Pro controller, but unfortunately, the others (not64, snes9xgx, fceugx, and vbagx) do not.

I installed all these emulators on my Wii U main menu using WUP Installer GX2. Is it possible to enhance Bloopair to allow Nintendont and WiiStation to detect my Nintendo Switch controller? Since they already support the Wii U Pro controller, I hope it wouldn't be too difficult to achieve this goal. It would be fantastic if the same could be done for not64 as well! That would be incredible!

**Comment by GaryOderNichts** [comment]
Bloopair does not and will never work in Wii mode. It's a separate part of the console.
