### ISSUE TITLE
Desconexión de mando de PS4 de forma abrupta 

### ISSUE THREAD

**Issue by DrakensanhLuger647** [GaryOderNichts/Bloopair#23]
La desconexión de este mando puede ser perjudicial en contadas ocasiones pero frecuentes afectando a los otros mandos conectados a la consola obligando a apagar la misma para solucionar el error.

**Comment by DrakensanhLuger647** [comment]
Mando testeado con varios juegos en multijugador para ver su funcionalidad y su comportamiento en títulos de todo tipo.

**Comment by GaryOderNichts** [comment]
Any chance you could translate that to English?
It's quite hard to understand since I don't speak Spanish.

**Comment by DrakensanhLuger647** [comment]
![16342400808461843227629289575087](https://user-images.githubusercontent.com/92545762/137383765-d5a134e3-657a-40a3-bab3-b773ddd5fa7b.jpg)

**Comment by DrakensanhLuger647** [comment]
I was playing Tekken and it disconnects but it appears connected with the red light when I went to unlink the control, the original pro control was unlinked and then it did not reconnect

**Comment by DrakensanhLuger647** [comment]
I'm going to test as primary control
