### ISSUE TITLE
REQUEST - 8BitDo Gbros. Wireless Adapter for Nintendo Switch

### ISSUE THREAD

**Issue by bigchieff93** [GaryOderNichts/Bloopair#36]
https://www.amazon.com/dp/B07JLF9PVG?ref=ppx_pop_mob_ap_share

Let me know if there are any files or info you need from me (I have one)

Thank you!

**Comment by GaryOderNichts** [comment]
Hmm I'd assume it emulates a normal Switch controller. Is it currently not working?

If not, can you see if this build works? https://github.com/GaryOderNichts/Bloopair/issues/25#issuecomment-974570090

**Comment by bigchieff93** [comment]
I just tried it and it connected, THANK YOU!!! (PS That adapter is amazing)
