### ISSUE TITLE
8BitDo Pro 2 Support

### ISSUE THREAD

**Issue by Redcarred2** [GaryOderNichts/Bloopair#41]
Hello, The WiiU cant detect the 8BitDo Pro 2 after initializing Bloopair.

**Comment by chrislachance** [comment]
Original 8BitDo Pro works just fine. I paired as an XBox controller

**Comment by GaryOderNichts** [comment]
I think this controller uses Bluetooth Low Energy, which is currently not supported.
Looking into adding support for it though.

**Comment by lm7nyne** [comment]
I was able to get my Pro 2 working by moving the switch on the back to X and then syncing. Only problem I've noticed is that the rumble motors won't stop once connected.

**Comment by Redcarred2** [comment]
> I was able to get my Pro 2 working by moving the switch on the back to X and then syncing. Only problem I've noticed is that the rumble motors won't stop once you move the hand over one of the icons on the screen. I saw another bug post for sn30 that had the same issue but that was fixed with a firmware update. My Pro 2 is up to date so I am at a loss.

This is a fix, I just made a profile with Rumble set to zero in the pro software
