### ISSUE TITLE
Add TV button shortcut

### ISSUE THREAD

**Issue by tehrzky** [GaryOderNichts/Bloopair#43]
is it possible? even with a combination.

**Comment by GaryOderNichts** [comment]
What do you mean? The TV button is on the gamepad not on a Pro Controller.

**Comment by tehrzky** [comment]
i see. sorry i thought gamepad and pro controller has the same function. 

im planning to use swipswapme tv  button shortcut. now planning to try and bind it to other button. 

tnx

**Comment by BaamAlex** [comment]
If that would be the case, you wouldn't need the gamepad anymore...

**Comment by GaryOderNichts** [comment]
Bloopair doesn't emulate a GamePad, so this isn't possible.
