### ISSUE TITLE
Nintendo Switch Pro Controller USB

### ISSUE THREAD

**Issue by OriCoding** [GaryOderNichts/Bloopair#46]
Hello I am creating an issue to ask you if you can make sure that we can connect a nintendo switch Pro controller to usb with bloopair, if possible keep me posted, thank you ^ _ ^.

**Comment by takoyaki99** [comment]
There’s another homebrew for that IIRC

**Comment by OriCoding** [comment]
@takoyaki99 what is this homebrew please?

**Comment by takoyaki99** [comment]
Sorry for not telling you before, I had forgotten what it’s called, but it’s called HID to VPAD

**Comment by GaryOderNichts** [comment]
Yeah, Bloopair doesn't handle any sort of USB connections.
Instead you can use [HIDtoVPAD](https://github.com/Maschell/hid_to_vpad/) for that.
