### ISSUE TITLE
Question: Power On or off console with Bloopair controller

### ISSUE THREAD

**Issue by Luigimeansme** [GaryOderNichts/Bloopair#48]
Topic. I'm wondering if there's a way I'm unaware of to power on or off the console using one of the controllers you've connected rather than the Gamepad or a Wii Remote. The official pro controller has a power button for this purpose, is there a way to replicate this button at all?

**Comment by GaryOderNichts** [comment]
Duplicate of https://github.com/GaryOderNichts/Bloopair/issues/6.
This is more or less controller specific though. I believe this already works with the Xbox Controller.
