### ISSUE TITLE
Mario Kart 8 not working with Bloopair Tiramisu

### ISSUE THREAD

**Issue by roxas10** [GaryOderNichts/Bloopair#51]
Hi, so I installed Tiramisu on my wii u with the bloopair module. I connected my switch controller (Its a OEM from aliexpress), and all the games work great, except Mario Kart 8 so that it won't work in the game, but on home menu yes.

**Comment by GaryOderNichts** [comment]
What do you mean by "not working"?
Does the game freeze / crash / black screen?
Or does the controller not send any input?
Make sure you don't press A on the gamepad after booting the game.

**Comment by roxas10** [comment]
The controller won't send any input.

**Comment by takoyaki99** [comment]
Did you update to the latest releases of Bloopair and Tiramisu?

**Comment by roxas10** [comment]
I installed Tiramisu today, so should be updated

**Comment by GaryOderNichts** [comment]
It works fine for me with an official switch pro.
Make sure to press A on the controller you actually want to use on the "Press A to start" screen.

**Comment by roxas10** [comment]
Maybe was that I pressed A too much time? I tried again and now it works.
