### ISSUE TITLE
Tiramisu Bloopair not working 

### ISSUE THREAD

**Issue by Nottoknow2** [GaryOderNichts/Bloopair#53]
I am trying to pair a Xbox one s controller to the Wii U and it does not pair.

**Comment by GaryOderNichts** [comment]
Is this a Series S/X controller or do you have the latest insider firmware on the controller? If so that's not compatible with Bloopair.
Otherwise make sure both the Wii U and Controller are in pairing mode and wait for a few seconds.

**Comment by Nottoknow2** [comment]
> Is this a Series S/X controller or do you have the latest insider firmware on the controller? If so that's not compatible with Bloopair. Otherwise make sure both the Wii U and Controller are in pairing mode and wait for a few seconds.

No it is a Xbox one controller and i don't have the insider firmware

**Comment by Nottoknow2** [comment]
Sorry to waste your time but it was a insider update i thought you had to enroll in it so i thought it was a normal update

**Comment by JohangHernandez** [comment]
For any others viewing this page trying to figure this out, you can roll back the firmware if you updated it.

[Check Out Here](https://answers.microsoft.com/en-us/xbox/forum/all/revertrollbackdowngrade-xbox-controller-firmware/25f07169-3244-4fe0-838c-949951b7c109?auth=1)
