### ISSUE TITLE
Error  : Failed to read local bda (Make sure Bloopair is active!)

### ISSUE THREAD

**Issue by AndyUlate** [GaryOderNichts/Bloopair#54]
Hi i need some help , when I use  Bloopair the wiiU screen is in black a sent the next message: 

Failed to read local bda (Make sure Bloopair is active!)

Please , confirm the steps to solve

**Comment by GaryOderNichts** [comment]
The latest Bloopair version and all newer ones will only be available as Tiramisu setup modules.
It looks like you're trying to launch the Pairing Menu without having Tiramisu or the Bloopair module installed.
You'll either have to use v0.5.0 or switch to Tiramisu by following https://wiiu.hacks.guide/#/.

**Comment by AndyUlate** [comment]
Thank's so much , it's great. I instaling "Tiramisu" and the swicht controller work on it.
