### ISSUE TITLE
Will Bloopair Version 0.5.1 no longer be Haxchi compatible?

### ISSUE THREAD

**Issue by fermel01** [GaryOderNichts/Bloopair#55]
I currently use Haxchi, I need to know if the version of bloopair is 0.5.1 or if it will open a version later for those of us who use haxchi?

Greetings, I love your work!

**Comment by GaryOderNichts** [comment]
Like stated in the release notes and the previous issue, newer Bloopair versions will only be compatible with Tiramisu.
So v0.5.1 won't be compatible with Haxchi.
You'll either have to switch to Tiramisu or use v0.5.0.

**Comment by eku** [comment]
@fermel01 you're free to fork this repo and maintain a haxchi comptible version.
