### ISSUE TITLE
[BUG] Switch Pro Controller (Pointer stuck in direction / buttons fail to respond)

### ISSUE THREAD

**Issue by TheAlienDrew** [GaryOderNichts/Bloopair#65]
Steps to recreate:

1. Make sure the Switch Controller is on, and set as the first controller (order may not matter, but not going to test different orders)
2. Open a channel (bug is different depending on if it's a native app or homebrew app opened):
  a. Open the Mii Channel (to access Homebrew Launcher), and while doing so, use the left stick, and have it constantly moving around. Once the Homebrew Launcher loads, you'll find that the pointer is stuck going constantly in one direction.
  b. Open any Wii U channel where a point is supported (e.g. Daily Log). Once the channel loads, the pointer won't even show up on screen, and all buttons fail to respond (at least for about 15 seconds ish).

**Comment by GaryOderNichts** [comment]
This is not a Bloopair issue. The Wii U reads the current stick position to calibrate the neutral position.
If you move around the stick while launching an app, the neutral position will be wrong.
This can even be done with an official Pro Controller.
To reset the neutral position while the controller is connected see: https://en-americas-support.nintendo.com/app/answers/detail/a_id/1107/~/how-to-reset-the-l-and-r-control-sticks-to-a-neutral-position-on-the-wii-u-pro
