### ISSUE TITLE
Is it compatible with this class of controls?

### ISSUE THREAD

**Issue by fermel01** [GaryOderNichts/Bloopair#68]
I am about to acquire a PowerA Nano Enhanced Wireless Controller for Nintend0 Switch
, and I wanted to know if it is compatible with Bloopair and if it can be assigned to the buttons that they have on the bottom of the Nano control.

I love your job!

Best regards!
![71yCdOQ4d0L _SL1500_](https://user-images.githubusercontent.com/83359710/180809832-cd277b14-62ff-4ff4-947b-fd9b77a792bf.jpg)

**Comment by GaryOderNichts** [comment]
If it works on an unmodified switch there is a pretty high chance that it will work with Bloopair as well.
