### ISSUE TITLE
[Feature] Swap A/B and X/Y

### ISSUE THREAD

**Issue by Janni9009** [GaryOderNichts/Bloopair#69]
For those of us wired to auto-adjust to a layout by controller type, it'd be nice to be able to swap A/B and X/Y to not press the wrong buttons all the time.

**Comment by GaryOderNichts** [comment]
[Bloopair v1.0.0](https://github.com/GaryOderNichts/Bloopair/releases/tag/v1.0.0) supports button remapping.
