### ISSUE TITLE
Bloopair pairing app hangs right after selecting from hbc

### ISSUE THREAD

**Issue by agentmike** [GaryOderNichts/Bloopair#78]
the app ( i need it for the ps3 controller) hangs right after selecting it from the hbc.
(the Load or Back button arent pressed yet.)

selecting Back doen'st work, selecting Load does'nt work.  only restart of the system by pressing power for 5 seconds brings me back to de Wii U menu.

installed according to the instruction with the rpx file in wiiu/environments/tiramisu/modules/setup/
and the app in de Wii\apps\bloopair_pair_menu\

i'm on version 0.5.3 of Bloopair and running latest version of Tiramisu

**Comment by GaryOderNichts** [comment]
The Hombrew Launcher channel version does not work properly with Tiramisu. Try using the one jnjected into Mii Maker instead.
