### ISSUE TITLE
Add Dualsense microphone and speaker support

### ISSUE THREAD

**Issue by Invictaz** [GaryOderNichts/Bloopair#8]
Some games use the Wiimote's speaker, the Dualsense and Dualshock 4 have also a speaker

See

https://github.com/Ryochan7/DS4Windows/blob/2f1d8d353253d7f2ab7edadd70888658f1dacd7c/DS4Windows/DS4Library/DS4Audio.cs

https://patchwork.kernel.org/project/linux-input/patch/20210215004549.135251-3-roderick@gaikai.com/

**Comment by GaryOderNichts** [comment]
The Wii U Pro Controller does not have a speaker.
