### ISSUE TITLE
[Question] Stadia Controller compatibility

### ISSUE THREAD

**Issue by FranzXaver** [GaryOderNichts/Bloopair#85]
Now that we are able to enable bluetooth on the Google Stadia controller, are there any plans to add this controller?

FYI you can enable bluetooh on the Stadia controller here:
https://stadia.google.com/controller/index.html

Thank you in advance.

Edit: I would gladly help to add it if I can

**Comment by GaryOderNichts** [comment]
Looks like the Stadia controller is using BLE which is not supported by Bloopair and most likely won't be supported in the future.

**Comment by FranzXaver** [comment]
Thanks Gary, I am trying to find out if the bluetooth controller could maybe support BLE, but I can't find any specs. 
It should be a Broadcomm BCM20702 (2878D-WIN-B2), right?

**Comment by Gius29** [comment]
I would be amazing to use Stadia controller with the wiiU
