### ISSUE TITLE
Can no longer compile

### ISSUE THREAD

**Issue by godreborn** [GaryOderNichts/Bloopair#87]
I'm trying to recompile bloopair, but now this happens.  I made no changes just to test it:

c:/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld.exe: unrecognized option '--no-warn-rwx-segments'
c:/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld.exe: use the --help option for usage information
collect2.exe: error: ld returned 1 exit status
make[2]: *** [/home/GODREBORN/Desktop/test/Bloopair/ios/ios_pad/Makefile:25: /home/GODREBORN/Desktop/test/Bloopair/ios/ios_pad/ios_pad.elf] Error 1
make[1]: *** [Makefile:108: build] Error 2
make: *** [Makefile:28: ios_pad] Error 2

**Comment by GaryOderNichts** [comment]
You need to update your devkitARM installation.
