### ISSUE TITLE
Add motion controls

### ISSUE THREAD

**Issue by Invictaz** [GaryOderNichts/Bloopair#9]
Add Dualshock 3 and Dualshock 4 and Joy-Con motion / gyro controls

Example

https://github.com/OperationNT414C/DSMotion/blob/master/kernel/main.c

I know the Wiiu Pro controller does not have a motion or gyro sensor, but the Wiimote does.

**Comment by Invictaz** [comment]
Seems that they act as a separate controller and some people like them to be disabled

https://github.com/RetroPie/RetroPie-Setup/issues/2436

**Comment by GaryOderNichts** [comment]
Emulating Wiimotes isn't a planned feature at the moment. And like you said, the Pro Controller doesn't have motion controls.
