### ISSUE TITLE
Allow usage with Nintendont and vWii mode

### ISSUE THREAD

**Issue by WildoBro** [GaryOderNichts/Bloopair#90]
This would likely be a pretty big change. The N64 controller works, but the actual n64 emulation isn't great. It would be awesome to use the n64 controller with the superior n64 emulation in vWii mode and when playing GC emulation via Nintnedont.

**Comment by WildoBro** [comment]
Sorry, not sure how to add the "enhancement" tag

**Comment by GaryOderNichts** [comment]
Bloopair works by patching parts of the Wii U mode which is not possible in vWii mode. So this won't be possible.
