### ISSUE TITLE
Failed to read local bda (Make sure bloopair is active!) error happens and i did everything but it still wont work

### ISSUE THREAD

**Issue by Natethebest20** [GaryOderNichts/Bloopair#91]
I did everything right I put the file in the same place and I can't get it to work it says the error code and i have tiramisu too. @GaryOderNichts or anyone please help me on this

**Comment by Natethebest20** [comment]
@GaryOderNichts please help me on this

**Comment by GaryOderNichts** [comment]
Can you post a screenshot of your `sd:/wiiu/environments/tiramisu/modules/setup/` folder?

**Comment by X-DE1** [comment]
I have the same error :/
Here is the screenshot of my sd:/wiiu/environments/tiramisu/modules/setup/          folder
![Captura de pantalla_2023-04-07_17-47-34](https://user-images.githubusercontent.com/101435795/230693750-c40a5d9b-39e2-463b-88fb-e62f80dc3859.png)
